# Databricks notebook source
# MAGIC %md
# MAGIC # Paso 3 — DDL de Silver
# MAGIC Registra las tablas Delta externas del dominio `flight-operations`.

# COMMAND ----------

# MAGIC %run ./00_config

# COMMAND ----------

if CATALOG != "workspace":
    raise ValueError("For this Free Edition lab, catalog must be workspace")

# COMMAND ----------

spark.sql(
    f"""
    CREATE TABLE IF NOT EXISTS {CATALOG}.{SILVER_SCHEMA}.flight_status_history (
        flight_instance_id STRING NOT NULL COMMENT 'Stable identifier of one monitored airport movement',
        event_id STRING NOT NULL COMMENT 'Identifier generated by the producer for the snapshot',
        observed_at_utc TIMESTAMP NOT NULL,
        source_system STRING NOT NULL,
        schema_version INT NOT NULL,
        flight_date DATE,
        flight_status STRING,
        monitored_airport_iata STRING NOT NULL,
        movement_type STRING NOT NULL,
        airline_name STRING,
        airline_iata STRING,
        airline_icao STRING,
        flight_key STRING NOT NULL,
        flight_number STRING,
        flight_iata STRING,
        flight_icao STRING,
        aircraft_registration STRING,
        aircraft_icao24 STRING,
        departure_airport STRING,
        departure_iata STRING,
        departure_scheduled_at_utc TIMESTAMP,
        departure_estimated_at_utc TIMESTAMP,
        departure_actual_at_utc TIMESTAMP,
        departure_delay_minutes INT,
        arrival_airport STRING,
        arrival_iata STRING,
        arrival_scheduled_at_utc TIMESTAMP,
        arrival_estimated_at_utc TIMESTAMP,
        arrival_actual_at_utc TIMESTAMP,
        arrival_delay_minutes INT,
        position_updated_at_utc TIMESTAMP,
        latitude DOUBLE,
        longitude DOUBLE,
        altitude_meters DOUBLE,
        direction_degrees DOUBLE,
        horizontal_speed_kmh DOUBLE,
        vertical_speed_kmh DOUBLE,
        is_ground BOOLEAN,
        bronze_record_id STRING NOT NULL,
        processed_at_utc TIMESTAMP NOT NULL
    )
    USING DELTA
    LOCATION '{SILVER_FLIGHT_STATUS_HISTORY_LOCATION}'
    COMMENT 'Validated and conformed history of Peru flight observations'
    TBLPROPERTIES (
        'quality' = 'silver',
        'domain' = 'flight-operations',
        'entity' = 'flights'
    )
    """
)

# COMMAND ----------

spark.sql(
    f"""
    CREATE TABLE IF NOT EXISTS {CATALOG}.{SILVER_SCHEMA}.current_flight_status (
        flight_instance_id STRING NOT NULL,
        last_event_id STRING NOT NULL,
        flight_date DATE,
        last_observed_at_utc TIMESTAMP NOT NULL,
        flight_status STRING,
        monitored_airport_iata STRING NOT NULL,
        movement_type STRING NOT NULL,
        airline_name STRING,
        airline_iata STRING,
        flight_key STRING NOT NULL,
        flight_number STRING,
        flight_iata STRING,
        aircraft_registration STRING,
        departure_airport STRING,
        departure_iata STRING,
        departure_scheduled_at_utc TIMESTAMP,
        departure_estimated_at_utc TIMESTAMP,
        departure_actual_at_utc TIMESTAMP,
        departure_delay_minutes INT,
        arrival_airport STRING,
        arrival_iata STRING,
        arrival_scheduled_at_utc TIMESTAMP,
        arrival_estimated_at_utc TIMESTAMP,
        arrival_actual_at_utc TIMESTAMP,
        arrival_delay_minutes INT,
        position_updated_at_utc TIMESTAMP,
        latitude DOUBLE,
        longitude DOUBLE,
        altitude_meters DOUBLE,
        horizontal_speed_kmh DOUBLE,
        is_ground BOOLEAN,
        updated_at_utc TIMESTAMP NOT NULL
    )
    USING DELTA
    LOCATION '{SILVER_CURRENT_FLIGHT_STATUS_LOCATION}'
    COMMENT 'Latest known status for each scheduled flight occurrence'
    TBLPROPERTIES (
        'quality' = 'silver',
        'domain' = 'flight-operations',
        'entity' = 'flights',
        'dataset_type' = 'current-state'
    )
    """
)

# COMMAND ----------

print("Silver DDL completed")
print(f"History: {CATALOG}.{SILVER_SCHEMA}.flight_status_history")
print(f"Current: {CATALOG}.{SILVER_SCHEMA}.current_flight_status")
print(f"History location: {SILVER_FLIGHT_STATUS_HISTORY_LOCATION}")
print(f"Current location: {SILVER_CURRENT_FLIGHT_STATUS_LOCATION}")
